#!/bin/bash
mkdir -p thumbnails
cp assets/about-poster.png thumbnails/about-poster-thmbn.png
cp assets/FromFortsToFarmans.png thumbnails/FromFortsToFarmans-thmbn.png
cp assets/RoadsOfMeaning.png thumbnails/RoadsOfMeaning-thmbn.png
cp assets/key-considerations.png thumbnails/key-considerations-thmbn.png
cp assets/valleyforge-memorial-gardens.png thumbnails/valleyforge-memorial-gardens-thmbn.png
cp assets/VFP_VisitorCenter.png thumbnails/VFP_VisitorCenter-thmbn.png
cp assets/tracks-through-time.png thumbnails/tracks-through-time-thmbn.png
cp assets/ValleyFriendsToFlourtown.png thumbnails/ValleyFriendsToFlourtown-thmbn.png
cp assets/RusticVFP.png thumbnails/RusticVFP-thmbn.png
cp assets/devon-culture-schools.png thumbnails/devon-culture-schools-thmbn.png
cp assets/OrangePointOfInterest.png thumbnails/OrangePointOfInterest-thmbn.png
cp assets/AWalkthroughDevonshire-2.png thumbnails/AWalkthroughDevonshire-2-thmbn.png
cp assets/MainLineAndVicinity.png thumbnails/MainLineAndVicinity-thmbn.png
cp assets/charlotte-everley-articles.png thumbnails/charlotte-everley-articles-thmbn.png
cp assets/blue-ribbon-radius.png thumbnails/blue-ribbon-radius-thmbn.png
cp assets/tracks-of-legacy.png thumbnails/tracks-of-legacy-thmbn.png
cp assets/BigPharma.png thumbnails/BigPharma-thmbn.png
cp assets/devon-og.jpg thumbnails/devon-og-thmbn.jpg
cp assets/cultural-footprint.png thumbnails/cultural-footprint-thmbn.png
cp assets/WomensRighhtAndTheMainLine.png thumbnails/WomensRighhtAndTheMainLine-thmbn.png
cp assets/FromRockAnthemsToRabbitTrails.png thumbnails/FromRockAnthemsToRabbitTrails-thmbn.png
cp assets/FromGardenStateGrindToMainLineEase.png thumbnails/FromGardenStateGrindToMainLineEase-thmbn.png
cp assets/devon-home-infographic.png thumbnails/devon-home-infographic-thmbn.png
cp assets/TheAllureOfTheMainLine.png thumbnails/TheAllureOfTheMainLine-thmbn.png
cp assets/RobertsElementary.png thumbnails/RobertsElementary-thmbn.png
cp assets/mainline-demographics.png thumbnails/mainline-demographics-thmbn.png
cp assets/AWalktroughDEVONSHIRE.png thumbnails/AWalktroughDEVONSHIRE-thmbn.png
cp assets/berwyn-og.jpg thumbnails/berwyn-og-thmbn.jpg
